### ISSUE TITLE
Side Menu Does not apper on v0.8.10 or v.0.8.11

### ISSUE THREAD

**Issue by mth211** [jonducrou/ha_visualiser#11]
**Side Menu does not appear**
Installation via HACS of v.10 or v.11 followed by a restart does not show the menu icon as expected
Checking to see if adding via Integration was still an option gave the output that integration cannot be set up from the UI

**To Reproduce**
1. Install either v.10 or v.11 from fresh
2. Restart HA'
3. Look for icon in side bar

**Expected behavior**
Icon in side bar should appear

**Environment (please complete the following information):**
 - Home Assistant Version: 2025.8.3
 - Integration Version: 0.8.10 & 0.8.11
 - Browser: Chrome

**Comment by schaffer970** [comment]
Same issue with .11. Had previously tried with.9 and had the same issue.

**Comment by jonducrou** [comment]
## 🔧 Experimental Fix Released - v0.8.12

I've released **v0.8.12** which attempts to address this panel registration issue. Since I was unable to reproduce the problem locally, this is an **experimental fix** based on my analysis of potential edge cases in the setup logic.

### 🛠️ What I Changed
The issue seemed to be related to early return conditions during Home Assistant startup that could prevent the panel from being registered if:
1. The integration partially initialized on a previous attempt
2. The panel registration failed but the service setup succeeded
3. Subsequent restarts would skip panel registration due to early returns

The fix adds:
- A new `_ensure_panel_registered()` function that always attempts panel registration
- Logic to retry panel registration even when services are already initialized
- Enhanced error handling and logging

### 🧪 Please Test
If you were experiencing this issue:

1. **Update to v0.8.12** via HACS  
2. **Restart Home Assistant**
3. **Check your sidebar** for "Entity Visualizer"

### 📋 If Issue Persists  
If the panel still doesn't appear, I need more details to investigate:

1. **Home Assistant logs** from startup (look for "ha_visualiser" entries)
2. **Browser console logs** (F12 → Console tab, look for errors)
3. **Your HA version** and **browser type**
4. **Installation method** (HACS, manual)
5. **When exactly** the issue started (was it working before? which version?)

### 🔗 Release Notes
Full details: https://github.com/jonducrou/ha_visualiser/releases/tag/v0.8.12

Thanks for your patience as we work through this! The lack of reproduction steps makes this tricky to debug, but I'm hopeful this addresses the root cause.

**Comment by HomeAssistantMaster** [comment]
Works for me now.  Thank you.

**Comment by bobclear** [comment]
Hello, I'll start with a premise: I'm writing in Italian with the help of a translator and I'm not very good with HA.
I did what you suggested: I installed version 0.8.12, but the menu item still doesn't appear.
I also tried to uninstall and reinstall.
- HA version 2025.8.3
- Browser: both Edge and Brave, but also from the app and from two different PCs.
- I installed it as an integration via HACS Custom Repositories.

I installed it for the first time yesterday.
I tried searching the system logs, but I didn't find anything with ha_visualiser. I'm afraid I might have looked in the wrong place.
Thank you

**Comment by PlayFaster** [comment]
#samehere

Just to flag that I am seeing the same issue, installed v12 today for the first time, no side-bar. This is with 2025.8.3. I've restarted and rebooted. Nothing in log file. I am seeing the same issue in my test/backup system which is on 2025.9.0. Not working on Chrome or Firefox. As per others, if I can check or provide anything, please let me know ...

**Comment by bobclear** [comment]
Thanks, I can confirm it works now. 0.08.13 / 2025.9. Great job on the integration, and thanks for the support!

**Comment by jburkett617** [comment]
it works for me now thanks so much :)

**Comment by mth211** [comment]
Also now resolved for me, thanks for getting it resolved

**Comment by Jano1959** [comment]
Same issue for me on v0.8.13. HA 2025.9.0
Tried removing, adding, updating HA.  
So far no joy.

**Comment by jonducrou** [comment]
> Same issue for me on v0.8.13. HA 2025.9.0
> Tried removing, adding, updating HA.  
> So far no joy.

Can you try adding via the integration page as a new integration? Let me know if its not working - I really want to work out this issue.

**Comment by douglove** [comment]
Thanks for the update it works for me. I really like it.
